services:
  front:
    image: node:22-alpine
    ports:
      - 5173:5173
    working_dir: /app
    volumes:
      - ./front:/app

    command: ssh -c "npm install && npm run dev"

  back:
    image: directus/directus
    ports:
        - 8055:8055
    environment:
      ADMIN_EMAIL: admin@enloused.com
      ADMIN_PASSWORD: 1234 
      # info BD
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: enloused
      DB_USER: user
      DB_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:17 
    environment:
      POSTGRES_DB: enloused
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./data/dump.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DESIGN: pepa-linha-dark
    depends_on:
      - db


